name: Deploy Worker

on:
  push:
    paths:
      - server/**
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          yarn
          yarn workspace shared build

      - name: Run test eslint and prettier
        run: yarn workspace server test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Wrangler Config
        run: |
          cat <<EOF > server/wrangler.toml
          ${{ secrets.WRANGLER_CONFIG }}
          EOF

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          yarn
          yarn workspace shared build

      - name: Build & Deploy Worker
        run: |
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          yarn workspace server deploy
