name: Deploy Worker

on:
  push:
    paths:
      - server/**
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Run test eslint and prettier
        run: yarn workspace server test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Wrangler Config
        run: |
          cd server
          cat <<EOF > wrangler.toml
          ${{ secrets.WRANGLER_CONFIG }}
          EOF
          cd ..

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "server"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
